services:
  backend_dummy:
    container_name: backendDummy
    build:
      context: ./srcs/backend
    # command: python manage.py runserver
    volumes:
      - ./srcs/backend/beePong:/usr/src/backend/beePong
      # - ./tests:/code/tests
  # db:
  #   image: postgres:16
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  nginx:
    container_name: nginx
    depends_on:
      - backend_dummy
    build:
      context: ./srcs/nginx
    volumes:
      - ./srcs/frontend:/var/www/html
    ports:
      - 443:443
    restart: on-failure