
services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} --password ${POSTGRES_PASSWORD}"] 
      # interval: 10s
      timeout: 5s
      retries: 5

  backendummy:
    container_name: backendummy
    build:
      context: ./srcs/backend
    volumes:
      - ./srcs/backend/beePong:/usr/src/backend/beePong
    env_file:
      - .env
    # ports:
      # - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1"]
      # interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: ./srcs/nginx
    volumes:
      - ./srcs/frontend:/var/www/html
    ports:
      - 443:443
    restart: on-failure
    depends_on:
      backendummy:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:

