services:
  backend_dummy:
    container_name: backendDummy
    build:
      context: ./srcs/backend
    ports:
      - 8000:8000
    # command: python manage.py runserver
    volumes:
      - ./srcs/backend/beePong:/usr/src/backend/beePong
      # - ./tests:/code/tests
  # db:
  #   image: postgres:16
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  # nginx: 
  #   container_name: nginx
  #   depends_on:
  #     - backendDummy
  #   build:
  #     context: ./srcs/nginx
  #   env_file:
  #     - .env
  #   volumes:
  #     - .srcs/backend/beePong:/beePong/app
  #   ports:
  #     - 127.0.0.1:8000:8000
  #   restart: on-failure