services:
  bpong:
    container_name: bpong
    build: .
    ports:
      - 127.0.0.1:8000:8000
    # command: python manage.py runserver
    volumes:
      - ./bpong:/bpong/app
      # - ./tests:/code/tests