services:
  dummy_pong:
    container_name: dummy_pong
    build: .
    ports:
      - 127.0.0.1:8000:8000
    # command: python manage.py runserver
    volumes:
      - ./dummy_pong:/dummy_pong/app
      # - ./tests:/code/tests