filebeat.inputs:
- type: filestream
  id: nginx-access-logs
  paths:
    - /usr/share/filebeat/nginx_logs/access.log

- type: filestream
  id: nginx-error-logs
  paths:
    - /usr/share/filebeat/nginx_logs/error.log

- type: filestream
  id: app-logs
  paths:
    - /usr/share/filebeat/app_logs/app.log

- type: filestream
  id: sys-logs
  paths:
    - /var/log/syslog

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_docker_metadata: ~

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

output.logstash:
  hosts: ["logstash01:5044"]

